#!/usr/bin/env python3
"""Export crawler JSON output into the site's static data file."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description="Export scraped data to site data file.")
    p.add_argument("--input", default="crawler/output/scraped.json", help="Input JSON from Scrapy")
    p.add_argument("--output", default="../YOMIKAZE/src/providers/scrapedData.ts", help="Output TypeScript file")
    args = p.parse_args(argv)

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Input file not found: {input_path}", file=sys.stderr)
        return 1

    data = json.loads(input_path.read_text(encoding="utf-8"))
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "// Auto-generated by export_site_data.py — do not edit manually.",
        "export interface RawScrapedItem {",
        "  source: string;",
        "  source_id: string;",
        "  title: string;",
        "  alt_titles: string[];",
        "  description?: string;",
        "  authors: string[];",
        "  genres: string[];",
        "  status?: string;",
        "  cover_url?: string;",
        "  url: string;",
        "  chapter_count?: string;",
        "}",
        "",
        "export const scrapedItems: RawScrapedItem[] = ",
        json.dumps(data, ensure_ascii=False, indent=2),
        ";",
        "",
    ]

    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[*] Exported {len(data)} items to {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
