/**
 * MangaFire adapter — browser-based source (mangafire.to).
 *
 * The site is WAF-protected and its JSON API requires a per-page `vrf`
 * protection token generated by `window.getProtectionToken`, so every call
 * goes through the shared BrowserScraper (one reused browser, bounded pages):
 *
 *   getLatest / getPopular → /api/top-titles (no vrf required)
 *   search                 → /filter?keyword=...&type=... (DOM)
 *   getDetails             → /api/titles/{hid} (vrf)
 *   getChapters            → title page DOM (chapter links, pager clicked)
 *   getChapterPages        → /api/chapters/{id} (vrf) → page image URLs
 *
 * Adapter behaviour matches the Python mangafire_catalog.py scraper that was
 * already in the project, ported to the JUKU TypeScript engine.
 */
import type { RawChapter, RawTitle } from '../normalizer.js'
import { stripHtml } from '../normalizer.js'
import type { BrowserScraper } from '../browser.js'
import type { SearchResult, SourceAdapter } from './SourceAdapter.js'

const BASE = 'https://mangafire.to'

interface MangaFireItem {
  url?: string
  title?: string
  type?: string
  rank?: number
}

interface MangaFireTitleData {
  title?: string
  slug?: string
  type?: string
  altTitles?: string[]
  synopsisHtml?: string
  description?: string
  authors?: Array<{ name?: string }>
  artists?: Array<{ name?: string }>
  genres?: Array<{ title?: string }>
  status?: string
  year?: number
  rating?: number
  rank?: number
  poster?: { small?: string; medium?: string; large?: string }
  url?: string
}

/** Extract the stable hid from a mangafire title URL (/title/<hid>-<slug>). */
export function hidFromUrl(url: string): string {
  const m = /\/title\/([^/?#]+)/.exec(url)
  if (!m) return ''
  return m[1].split('-')[0]
}

export class MangaFireAdapter implements SourceAdapter {
  readonly id = 'mangafire'
  readonly label = 'MangaFire (browser)'
  readonly mode = 'browser' as const
  readonly usesBrowser = true

  constructor(private readonly scraper: BrowserScraper) {}

  private toRawTitle(item: MangaFireItem, hid?: string): RawTitle {
    const id = hid ?? hidFromUrl(item.url ?? '')
    return {
      title: item.title ?? id,
      alternativeTitles: [],
      slug: id,
      source: this.id,
      sourceUrl: item.url
        ? item.url.startsWith('http')
          ? item.url
          : `https://mangafire.to${item.url}`
        : `https://mangafire.to/title/${id}`,
      type: item.type,
      rating: item.rank !== undefined ? 1000 / Math.max(1, item.rank) : undefined,
      chapters: [],
    }
  }

  async search(query: string, limit = 20): Promise<SearchResult> {
    const found = new Map<string, RawTitle>()
    for (const kind of ['manga', 'manhua', 'manhwa']) {
      const url = `${BASE}/filter?keyword=${encodeURIComponent(query)}&type=${kind}`
      const links = await this.scraper.withPage<Array<{ href: string; text: string }>>(
        async page =>
          page.evaluate(() =>
            Array.from(document.querySelectorAll('a[href*="/title/"]'))
              .map(a => {
                const anchor = a as HTMLAnchorElement
                const img = a.querySelector('img')
                const t =
                  a.getAttribute('title') ||
                  (img ? img.getAttribute('alt') : '') ||
                  (a.textContent || '').replace(/\s+/g, ' ').trim()
                return { href: anchor.href ?? '', text: (t || '').trim() }
              })
              .filter(x => x.href),
          ),
        { url, waitMs: 2500 },
      )
      for (const l of links ?? []) {
        const hid = hidFromUrl(`https://mangafire.to${l.href}`)
        if (!hid || found.has(hid)) continue
        found.set(hid, this.toRawTitle({ title: l.text || hid, url: l.href }, hid))
        if (found.size >= limit) return { titles: [...found.values()] }
      }
      if (found.size >= limit) break
    }
    return { titles: [...found.values()] }
  }

  async getDetails(ref: string): Promise<RawTitle | null> {
    const data = await this.scraper.apiGet<{ data?: MangaFireTitleData }>(BASE, `/api/titles/${encodeURIComponent(ref)}`)
    const d = data?.data
    if (!d) return null
    const poster = d.poster ?? {}
    const cover = poster.large || poster.medium || poster.small
    const authors = (d.authors ?? []).map(a => a.name).filter((x): x is string => Boolean(x))
    const artists = (d.artists ?? []).map(a => a.name).filter((x): x is string => Boolean(x))
    return {
      title: d.title ?? d.slug ?? ref,
      alternativeTitles: d.altTitles ?? [],
      slug: d.slug ?? ref,
      description: stripHtml(d.synopsisHtml) ?? d.description,
      cover,
      author: authors[0],
      artist: artists[0] ?? authors[1],
      genres: (d.genres ?? []).map(g => g.title).filter((x): x is string => Boolean(x)),
      status: d.status,
      rating: d.rating,
      type: d.type,
      year: d.year,
      source: this.id,
      sourceUrl: d.url ? `https://mangafire.to${d.url}` : `https://mangafire.to/title/${ref}`,
      chapters: [],
    }
  }

  async getChapters(ref: string): Promise<RawChapter[]> {
    const items = await this.scraper.withPage<Array<{ id: number; number: number; url: string }>>(
      async page => {
        const collected = new Map<number, { id: number; number: number; url: string }>()
        for (let pageNum = 1; pageNum <= 50; pageNum += 1) {
          const rows = await page.evaluate(() => {
            const out: Array<{ id: number; number: number; url: string }> = []
            document.querySelectorAll('a[href*="/chapter/"]').forEach(el => {
              const a = el as HTMLAnchorElement
              const text = a.textContent || ''
              const numMatch = text.match(/(\d+)/)
              const idMatch = (a.href || '').match(/chapter\/(\d+)/)
              if (numMatch && idMatch) {
                out.push({ id: Number(idMatch[1]), number: Number(numMatch[1]), url: a.href })
              }
            })
            return out
          })
          for (const r of rows) collected.set(r.number, r)
          if (!rows.length) break
          // Find the pager; if there is a next page, click it.
          const pagers = await page.evaluate(() =>
            Array.from(document.querySelectorAll('.npager__num'))
              .map(b => Number((b.textContent || '').trim()))
              .filter(n => Number.isFinite(n)),
          )
          const lastPage = pagers.length ? Math.max(...pagers) : pageNum
          if (pageNum >= lastPage) break
          const clicked = await page.evaluate(
            next =>
              Array.from(document.querySelectorAll('.npager__num')).some(b => {
                if (Number((b.textContent || '').trim()) === next) {
                  ;(b as HTMLElement).click()
                  return true
                }
                return false
              }),
            pageNum + 1,
          )
          if (!clicked) break
          await page.waitForTimeout(3000)
        }
        return [...collected.values()].sort((a, b) => a.number - b.number)
      },
      { url: `${BASE}/title/${encodeURIComponent(ref)}`, waitMs: 3500 },
    )

    return (items ?? []).map(c => ({
      chapterNumber: c.number,
      chapterTitle: `Chapter ${c.number}`,
      chapterUrl: c.url,
      pages: [],
    }))
  }

  async getChapterPages(ref: string): Promise<string[]> {
    let id = ref
    const m = /\/chapter\/(\d+)/.exec(ref)
    if (m) id = m[1]
    const data = await this.scraper.apiGet<{ data?: { pages?: Array<{ url?: string }> } }>(
      BASE,
      `/api/chapters/${encodeURIComponent(id)}`,
    )
    const pages = (data?.data?.pages ?? []).map(p => p.url).filter((x): x is string => Boolean(x))
    if (pages.length) return pages
    // Fallback: read <img> elements on the reader page.
    const dom = await this.scraper.withPage<string[]>(
      page =>
        page.evaluate(() =>
          Array.from(document.querySelectorAll('img'))
            .map(img => img.currentSrc || img.src || img.getAttribute('data-src') || '')
            .filter(u => u.startsWith('http')),
        ),
      { url: `${BASE}/chapter/${encodeURIComponent(id)}`, waitMs: 3000 },
    )
    return dom ?? []
  }

  async getLatest(limit = 20): Promise<RawTitle[]> {
    return this.topTitles('trending', '7', limit)
  }

  async getPopular(limit = 20): Promise<RawTitle[]> {
    return this.topTitles('trending', '30', limit)
  }

  private async topTitles(type: string, days: string, limit: number): Promise<RawTitle[]> {
    const data = await this.scraper.withPage<{ items?: MangaFireItem[] }>(
      async page => {
        const resp = await page.request.get(`${BASE}/api/top-titles?type=${type}&days=${days}&limit=30`, {
          timeout: 15_000,
        })
        if (resp.status() === 403 || resp.status() === 429) {
          throw new Error(`top-titles returned ${resp.status()} (blocked)`)
        }
        if (resp.status() !== 200) return { items: [] }
        return ((await resp.json()) as { items?: MangaFireItem[] }) ?? { items: [] }
      },
      { url: BASE, waitMs: 2500 },
    )
    const items = data?.items ?? []
    const out: RawTitle[] = []
    for (const it of items.slice(0, limit)) {
      const hid = hidFromUrl(it.url ?? '')
      if (!hid) continue
      out.push(this.toRawTitle(it, hid))
    }
    return out
  }
}
